version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Check if PR
          command: | 
            if [[ -z "$CIRCLE_PULL_REQUEST" ]]; then
              echo "This was not triggered by a PR. The build will now exit"
              circleci-agent step halt
            fi
      - run: echo "This is a PR"

workflows:
  workflow1:
    jobs:
      - build
