version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Check if PR
          command: |
            if [[ ! -z "$CIRCLE_PULL_REQUEST" ]]; then
              echo "PR"
            fi

workflows:
  workflow1:
    jobs:
      - build
